-- CreateTable
CREATE TABLE "veiculos" (
    "id" SERIAL NOT NULL,
    "placa" TEXT NOT NULL,
    "renavam" TEXT,
    "ativo" BOOLEAN NOT NULL DEFAULT true,
    "cadastro_verificado" BOOLEAN NOT NULL DEFAULT false,
    "dt_criacao" TIMESTAMP(3) NOT NULL,
    "dt_atualizacao" TIMESTAMP(3) NOT NULL,
    "id_vehicle_customer" INTEGER,

    CONSTRAINT "veiculos_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "proprietarios" (
    "ID" SERIAL NOT NULL,
    "NOME_PROP" TEXT NOT NULL,
    "ANTT_PROP" TEXT,
    "STATUS_ANTT" TEXT,
    "DT_VALIDADE_ANTT" TIMESTAMP(3),
    "CPF_CNPJ_PROP" TEXT NOT NULL,
    "ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "CADASTRO_VERIFICADO" BOOLEAN NOT NULL DEFAULT false,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "proprietarios_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "motoristas" (
    "ID" SERIAL NOT NULL,
    "NOME_MOT" TEXT NOT NULL,
    "CPF_MOT" TEXT NOT NULL,
    "CNH_MOT" TEXT,
    "NOME_PAI" TEXT,
    "NOME_MAE" TEXT,
    "CATEGORIA_CNH_MOT" TEXT,
    "COD_SITUACAO_CNH_MOT" TEXT,
    "DT_VALIDADE_CNH" TIMESTAMP(3),
    "DT_EMISSAO_CNH" TIMESTAMP(3),
    "DT_PRIMEIRA_CNH" TIMESTAMP(3),
    "DT_NASCIMENTO" TEXT,
    "FOTO_MOTORISTA" TEXT,
    "ATIVO" BOOLEAN NOT NULL DEFAULT true,
    "CADASTRO_VERIFICADO" BOOLEAN NOT NULL DEFAULT false,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "motoristas_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "viagens" (
    "ID" SERIAL NOT NULL,
    "IDCLIENT" INTEGER NOT NULL,
    "NUMERO_CLIENTE" TEXT NOT NULL,
    "DT_VIAGEM" TIMESTAMP(3) NOT NULL,
    "MERCADORIA" TEXT NOT NULL,
    "CIDADE_ORIGEM" TEXT NOT NULL,
    "CIDADE_DESTINO" TEXT NOT NULL,
    "IDMOTORISTA" INTEGER NOT NULL,
    "IDPROPRIETARIO" INTEGER NOT NULL,
    "IDVEICULO" INTEGER NOT NULL,
    "CARRETA1" TEXT,
    "CARRETA2" TEXT,
    "CARRETA3" TEXT,
    "CARRETA4" TEXT,
    "VIAGEM_CANCELADO" TEXT NOT NULL,
    "DT_CANCELAMENTO" TIMESTAMP(3),
    "DT_CLIENTE" TIMESTAMP(3) NOT NULL,
    "DT_CRIACAO" TIMESTAMP(3) NOT NULL,
    "DT_ATUALIZACAO" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "viagens_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "integracao_sankhya" (
    "id" SERIAL NOT NULL,
    "last_sync" TIMESTAMP(3) NOT NULL,
    "type_sync" TEXT NOT NULL,
    "page" INTEGER NOT NULL,
    "table_name" TEXT NOT NULL,

    CONSTRAINT "integracao_sankhya_pkey" PRIMARY KEY ("id")
);
